---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: create-cluster-rolebinding
  name: create-cluster-rolebinding
spec:
  template:
    metadata:
      labels:
        run: create-cluster-rolebinding
    spec:
      containers:
        - name: curl
          image: curlimages/curl:7.70.0
          command: ["/bin/sh", "-c"]
          args:
            [
              'curl -s --fail -X POST $(ENDPOINT) -H "Content-Type: application/json;charset=utf-8" -H "Authorization: Basic $(BASIC_AUTH)" --data ''{"generated_for_user":"test-user","roleName":"template-cluster-resources___admin","subjects":[{"kind":"ServiceAccount","name":"test-user","namespace":"permission-manager-e2e"}],"clusterRolebindingName":"test-user___template-cluster-resources___admin"}''',
            ]
          env:
            - name: ENDPOINT
              value: http://permission-manager.permission-manager-e2e.svc.cluster.local:80/api/create-cluster-rolebinding
            - name: BASIC_AUTH
              value: YWRtaW46YWRtaW4=
      restartPolicy: OnFailure
