---
builds:
  - skip: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  extra_files:
    - glob: deployments/kubernetes/seeds/crd.yml
    - glob: deployments/kubernetes/seeds/seed.yml
    - glob: deployments/kubernetes/deploy.yml
