version: "3.4"
services:
  frontend:
    build:
      dockerfile: development/frontend.dockerfile
      context: .
    volumes:
      - ./:/app
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4002"
      REACT_APP_BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - "4001:3000"
    networks:
     - kind

  backend:
    environment:
      IS_LOCAL_DEVELOPMENT: "true"
      CLUSTER_NAME: ${CLUSTER_NAME}
      CONTROL_PLANE_ADDRESS: ${CONTROL_PLANE_ADDRESS}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      NAMESPACE: ${NAMESPACE}
      PORT: 4005
    ports:
      - "4002:4005"
    build:
      dockerfile: development/backend.dockerfile
      context: .
    volumes:
      - ./:/app
      - ./.kubeconfig-backend:/root/.kube/config
    networks:
      - kind

networks:
  kind:
    external: true
