## PERMISSION MANAGER UI ##
FROM node:18-alpine3.17 as ui-builder
RUN mkdir /app
COPY web-client /app

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /app
RUN yarn install && yarn build


# Start Nginx and serve the static files
CMD ["yarn", "start"]

# RELEASE
# CMD ["nginx", "-g", "daemon off;"]

# FROM nginx:latest

# COPY --from=ui-builder /app/build /usr/share/nginx/html

# COPY --from=ui-builder /app/nginx.conf etc/nginx/nginx.conf

# EXPOSE 4001
