## PERMISSION MANAGER UI ##
FROM node:18-alpine3.17 as ui-builder
RUN mkdir /app
COPY web-client /app

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /app
RUN yarn install && yarn build

ENTRYPOINT ["yarn", "start"]

# RELEASE
# TODO create production behaviour
# FROM nginx:latest

# COPY --from=ui-builder /app/build /usr/share/nginx/html

# COPY --from=ui-builder /app/nginx.conf etc/nginx/nginx.conf

# EXPOSE 4001

# CMD ["nginx", "-g", "daemon off;"]
