## PERMISSION MANAGER UI ##

# DEVELOPMENT
FROM node:18-alpine3.17 as ui-development
RUN mkdir /app
COPY web-client /app

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /app
RUN yarn install && yarn build

ENTRYPOINT ["yarn", "start"]

# RELEASE
# TODO test this draft and convert it for production
FROM nginx:latest as release

COPY --from=ui-development /app/build /usr/share/nginx/html

COPY --from=ui-development /app/nginx.conf etc/nginx/nginx.conf

EXPOSE 4001

CMD ["nginx", "-g", "daemon off;"]
