apiVersion: v1
kind: Secret
metadata:
  name: {{ include "permission-manager.fullname" . }} 
  labels:
    {{- include "permission-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: {{ .Values.config.clusterName }} 
  CONTROL_PLANE_ADDRESS: {{ .Values.config.controlPlaneAddress }}
  BASIC_AUTH_PASSWORD: {{ (randAlpha 16) | b64enc | quote }}

