{{- if not .Values.secret.exists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{include "permission-manager.fullname" .}}
  labels: {{- include "permission-manager.labels" . | nindent 4}}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: {{required  ".config.clusterName is required. Its value will be used in the generated user kubeconfig to identify the cluster." .Values.config.clusterName}}
  CONTROL_PLANE_ADDRESS: {{required ".config.controlPlaneAddress is required. Its value will be used in the generated user kubeconfig as the address of the Kubernetes API server." .Values.config.controlPlaneAddress}}
  BASIC_AUTH_PASSWORD: {{required "config.basicAuthPassword is required. Its value will be used as the password to access Permission Manager's UI" .Values.config.basicAuthPassword}}
{{- end }}